#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/proc/cygdrive/c/Users/DELL/Downloads/Classroom-Supply-Tracker (2)/node_modules/.pnpm/orval@8.9.1_prettier@3.8.3_typescript@5.9.3/node_modules/orval/node_modules:/proc/cygdrive/c/Users/DELL/Downloads/Classroom-Supply-Tracker (2)/node_modules/.pnpm/orval@8.9.1_prettier@3.8.3_typescript@5.9.3/node_modules:/proc/cygdrive/c/Users/DELL/Downloads/Classroom-Supply-Tracker (2)/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/proc/cygdrive/c/Users/DELL/Downloads/Classroom-Supply-Tracker (2)/node_modules/.pnpm/orval@8.9.1_prettier@3.8.3_typescript@5.9.3/node_modules/orval/node_modules:/proc/cygdrive/c/Users/DELL/Downloads/Classroom-Supply-Tracker (2)/node_modules/.pnpm/orval@8.9.1_prettier@3.8.3_typescript@5.9.3/node_modules:/proc/cygdrive/c/Users/DELL/Downloads/Classroom-Supply-Tracker (2)/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../orval/dist/bin/orval.mjs" "$@"
else
  exec node  "$basedir/../orval/dist/bin/orval.mjs" "$@"
fi
# cmd-shim-target=C:/Users/DELL/Downloads/Classroom-Supply-Tracker (2)/backend/api-spec/node_modules/orval/dist/bin/orval.mjs
